trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
# Build runs in parallel
- template: build-stage.yml
  parameters:
    stageName: BUILD
    jobName: BuildJob
    runTimeInSeconds: 60

# Deploy runs in parallel
- template: deploy-stage.yml
  parameters:
    stageName: DEPLOY
    jobName: DeployJob
    runTimeInSeconds: 180

# Post deploy waits for both
- template: post-deploy-stage.yml
  parameters:
    stageName: POST_DEPLOY
    jobName: PostDeployJob
    runTimeInSeconds: 120
