trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: templates/stages/build-stage.yml
  parameters:
    stageName: BUILD
    jobName: BuildJob
    runTimeInSeconds: 180   # 3 minutes

- template: templates/stages/deploy-stage.yml
  parameters:
    stageName: DEPLOY
    jobName: DeployJob
    runTimeInSeconds: 300   # 5 minutes

- template: templates/stages/post-deploy-stage.yml
  parameters:
    stageName: POST_DEPLOY
    jobName: PostDeployJob
    runTimeInSeconds: 120   # 2 minutes
