trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: build-pipeline.yml
  parameters:
    stageName: BUILD
    jobName: BuildJob
    runTimeInSeconds: 180   # 3 minutes

- template: deploy-pipeline.yml
  parameters:
    stageName: DEPLOY
    jobName: DeployJob
    runTimeInSeconds: 300   # 5 minutes

- template: post-deploy-pipeline.yml
  parameters:
    stageName: POST_DEPLOY
    jobName: PostDeployJob
    runTimeInSeconds: 120   # 2 minutes
